### PR TITLE
Stop redirecting port 8080 to https

### LINKED ISSUE #3: Forcing https breaks most local gateways
[Here](https://github.com/aboutDavid/p2pbin/blob/9e20721621ff2da3ce34201b9b3b492aecb77b1a/index.html#L93), it forces it to switch to https no matter what. However, as most people run their local gateway on port 8080, this doesn't work and instead blocks you from connecting. This should either be removed or first check that it's on a port that supports https.

### PR DESCRIPTION
**Pull request by unbeatable-101**
Closes #3

### CODE REVIEW

**Review by aboutDavid — CHANGES_REQUESTED** [review]
There is no `and` in javascript. Can you make this into an `&&` please? (line 93)

**Comment by unbeatable-101** [comment]
Odd, I had built it and it worked

**Comment by aboutDavid** [comment]
> Odd, I had built it and it worked

I think that means that vercel was able to deploy it.

**Comment by unbeatable-101** [comment]
> > Odd, I had built it and it worked
> 
> I think that means that vercel was able to deploy it.

No, I built it on my machine and hosted it on IPFS, maybe it just ignored that part of the code entirely.

**Comment by aboutDavid** [comment]
> > > Odd, I had built it and it worked
> > 
> > 
> > I think that means that vercel was able to deploy it.
> 
> No, I built it on my machine and hosted it on IPFS, maybe it just ignored that part of the code entirely.

🤷‍♂️ idk, if there is an `and`, I think I would just keep using `&&` forcompatibilityy reasons

**Pull request merged**
